// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CreateForm.TestCases.Login
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CreateFormLogin", Description="\tCreate Member in jobsdb.com", SourceFile="TestCases\\Login\\CreateFormLogin.feature", SourceLine=0)]
    public partial class CreateFormLoginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateFormLogin.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateFormLogin", "\tCreate Member in jobsdb.com", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CS-001 user can be created login for join member in jobsdb.com", new string[] {
                "mytag"}, SourceLine=4)]
        public virtual void CS_001UserCanBeCreatedLoginForJoinMemberInJobsdb_Com()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CS-001 user can be created login for join member in jobsdb.com", new string[] {
                        "mytag"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("user is at the home page jobsdb", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("Navigate to Sign Up page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First_name",
                        "Last_name",
                        "Email",
                        "Password"});
            table1.AddRow(new string[] {
                        "cobasekali",
                        "coba",
                        "glddS@yahoo.com",
                        "cobalogin123"});
#line 8
 testRunner.When("user created a profile in form sign up", ((string)(null)), table1, "When ");
#line 11
 testRunner.And("Click on the create profile button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value",
                        "Value",
                        "Value"});
            table2.AddRow(new string[] {
                        "How long is your total work experience?",
                        "1 year",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "What is your latest job?",
                        "Quality Assurance",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "Who is your latest employer?",
                        "PT.Testing",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "How long have you been working here?",
                        "Jan",
                        "2017",
                        ""});
            table2.AddRow(new string[] {
                        "How would you classify your latest job?",
                        "Information Technology (IT)",
                        "IT Auditing",
                        ""});
            table2.AddRow(new string[] {
                        "In what industry is your latest employer?",
                        "Health & Beauty Care",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "What are your salary expectations?",
                        "Monthly",
                        "4000000",
                        "5000000"});
            table2.AddRow(new string[] {
                        "What is your highest education?",
                        "Diploma",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "What is your nationality?",
                        "Indonesia",
                        "",
                        ""});
            table2.AddRow(new string[] {
                        "Where do you live?",
                        "Indonesia",
                        "Banten",
                        "Tangerang"});
#line 12
 testRunner.And("user Input data about yourself", ((string)(null)), table2, "And ");
#line 24
 testRunner.And("Click on the continue button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.Then("the user can be access to login in jobsdb for search job", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
